In [1]:
import torch
import torch.nn as nn
import math
import jieba
# from dataloader import TrainDataset
from transformers import BertTokenizer, BertModel

d:\environment\Anaconda\envs\test\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
max_len = 10
d_model = 5
pos = torch.arange(0, max_len).float().unsqueeze(1)
print(pos)
_2i = torch.arange(0, d_model, step=1).float()
print(_2i)

encoder=torch.zeros(max_len, d_model)
print(encoder)
encoder[:, 0::2] = 1
print(encoder)
encoder[:, 1::2] = 2
print(encoder)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
tensor([0., 1., 2., 3., 4.])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]])
tensor([[1., 2., 1., 2., 1.],
        [1., 2., 1., 2., 1.],
        [1., 2., 1., 2., 1.],
        [1., 2., 1., 2., 1.],
        [1., 2., 1., 2., 1.],
        [1., 2., 1., 2., 1.],
        [1., 2., 1., 2., 1.],
        [1., 2., 1

In [10]:
a=torch.zeros(3,2)
b=torch.ones(3,2)
c=torch.cat((a,b),dim=0)
print(c)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
